[10-14-2024 11:28:39 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:28:39 AM] Starting up TCP server on localhost:61505
[10-14-2024 11:28:39 AM] Flet app has started...
[10-14-2024 11:28:39 AM] App session started
[10-14-2024 11:28:51 AM] Future exception was never retrieved
future: <Future finished exception=ValueError('time data "BAD DATE" doesn\'t match format "%a %b %d %Y %H:%M:%S", at position 33. You might want to try:\n    - passing `format` if your strings have a consistent format;\n    - passing `format=\'ISO8601\'` if your strings are all ISO8601 but not necessarily in exactly the same format;\n    - passing `format=\'mixed\'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.')>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 161, in main_service
    process_file()
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 128, in process_file
    csv_file[' DateTime'] = pd.to_datetime(csv_file[' DateTime']) # Convert DateTime column to iso datetime format
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 1067, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 433, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 467, in _array_strptime_with_fallback
    result, tz_out = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 501, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 451, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 583, in pandas._libs.tslibs.strptime._parse_with_format
ValueError: time data "BAD DATE" doesn't match format "%a %b %d %Y %H:%M:%S", at position 33. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
[10-14-2024 11:29:30 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:29:30 AM] Starting up TCP server on localhost:61505
[10-14-2024 11:29:30 AM] Flet app has started...
[10-14-2024 11:29:30 AM] App session started
[10-14-2024 11:29:37 AM] Future exception was never retrieved
future: <Future finished exception=ValueError('time data "BAD DATE" doesn\'t match format "%a %b %d %Y %H:%M:%S", at position 33. You might want to try:\n    - passing `format` if your strings have a consistent format;\n    - passing `format=\'ISO8601\'` if your strings are all ISO8601 but not necessarily in exactly the same format;\n    - passing `format=\'mixed\'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.')>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 161, in main_service
    process_file()
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 128, in process_file
    csv_file[' DateTime'] = pd.to_datetime(csv_file[' DateTime']) # Convert DateTime column to iso datetime format
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 1067, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 433, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 467, in _array_strptime_with_fallback
    result, tz_out = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 501, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 451, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 583, in pandas._libs.tslibs.strptime._parse_with_format
ValueError: time data "BAD DATE" doesn't match format "%a %b %d %Y %H:%M:%S", at position 33. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
[10-14-2024 11:30:01 AM] Future exception was never retrieved
future: <Future finished exception=ValueError('time data "BAD DATE" doesn\'t match format "%a %b %d %Y %H:%M:%S", at position 33. You might want to try:\n    - passing `format` if your strings have a consistent format;\n    - passing `format=\'ISO8601\'` if your strings are all ISO8601 but not necessarily in exactly the same format;\n    - passing `format=\'mixed\'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.')>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 161, in main_service
    process_file()
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 128, in process_file
    csv_file[' DateTime'] = pd.to_datetime(csv_file[' DateTime']) # Convert DateTime column to iso datetime format
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 1067, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 433, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 467, in _array_strptime_with_fallback
    result, tz_out = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 501, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 451, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 583, in pandas._libs.tslibs.strptime._parse_with_format
ValueError: time data "BAD DATE" doesn't match format "%a %b %d %Y %H:%M:%S", at position 33. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
[10-14-2024 11:30:14 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:30:14 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:30:14 AM] Flet app has started...
[10-14-2024 11:30:14 AM] App session started
[10-14-2024 11:30:23 AM] Future exception was never retrieved
future: <Future finished exception=ValueError('time data "BAD DATE" doesn\'t match format "%a %b %d %Y %H:%M:%S", at position 33. You might want to try:\n    - passing `format` if your strings have a consistent format;\n    - passing `format=\'ISO8601\'` if your strings are all ISO8601 but not necessarily in exactly the same format;\n    - passing `format=\'mixed\'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.')>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 161, in main_service
    process_file()
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 128, in process_file
    csv_file[' DateTime'] = pd.to_datetime(csv_file[' DateTime']) # Convert DateTime column to iso datetime format
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 1067, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 433, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\tools\datetimes.py", line 467, in _array_strptime_with_fallback
    result, tz_out = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 501, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 451, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 583, in pandas._libs.tslibs.strptime._parse_with_format
ValueError: time data "BAD DATE" doesn't match format "%a %b %d %Y %H:%M:%S", at position 33. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
[10-14-2024 11:33:21 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:33:21 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:33:21 AM] Flet app has started...
[10-14-2024 11:33:21 AM] App session started
[10-14-2024 11:33:42 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:33:42 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:33:42 AM] Flet app has started...
[10-14-2024 11:33:42 AM] App session started
[10-14-2024 11:33:52 AM] csv process: Completed in 8ms
[10-14-2024 11:36:01 AM] Service Closed: Completed in 0ms
[10-14-2024 11:36:03 AM] csv process: Completed in 6ms
[10-14-2024 11:37:05 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:37:05 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:37:05 AM] Flet app has started...
[10-14-2024 11:37:05 AM] App session started
[10-14-2024 11:37:14 AM] INVALID FORMATS FOUND IN INPUT CSV FILE: Completed in 0ms
[10-14-2024 11:37:14 AM] csv process: Completed in 14ms
[10-14-2024 11:37:38 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:37:38 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:37:38 AM] Flet app has started...
[10-14-2024 11:37:38 AM] App session started
[10-14-2024 11:38:51 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:38:51 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:38:51 AM] Flet app has started...
[10-14-2024 11:38:51 AM] App session started
[10-14-2024 11:39:09 AM] csv process: Completed in 1484ms
[10-14-2024 11:39:42 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:39:42 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:39:42 AM] Flet app has started...
[10-14-2024 11:39:42 AM] App session started
[10-14-2024 11:40:00 AM] INVALID DATE FOUND: Completed in 0ms
[10-14-2024 11:40:00 AM] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED: Completed in 0ms
[10-14-2024 11:40:00 AM] csv process: Completed in 13ms
[10-14-2024 11:44:02 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:44:02 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:44:02 AM] Flet app has started...
[10-14-2024 11:44:02 AM] App session started
[10-14-2024 11:44:33 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:44:33 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:44:33 AM] Flet app has started...
[10-14-2024 11:44:33 AM] App session started
[10-14-2024 11:45:23 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:45:23 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:45:23 AM] Flet app has started...
[10-14-2024 11:45:23 AM] App session started
[10-14-2024 11:45:32 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:45:32 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:45:32 AM] Flet app has started...
[10-14-2024 11:45:32 AM] App session started
[10-14-2024 11:45:41 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:45:41 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:45:41 AM] Flet app has started...
[10-14-2024 11:45:42 AM] App session started
[10-14-2024 11:46:10 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:46:10 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:46:10 AM] Flet app has started...
[10-14-2024 11:46:10 AM] App session started
[10-14-2024 11:48:10 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:48:10 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:48:10 AM] Flet app has started...
[10-14-2024 11:48:10 AM] App session started
[10-14-2024 11:48:28 AM] csv process: Completed in 719ms
[10-14-2024 11:50:15 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:50:15 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:50:15 AM] Flet app has started...
[10-14-2024 11:50:15 AM] App session started
[10-14-2024 11:50:22 AM] INVALID DATE FOUND: Completed in 0ms
[10-14-2024 11:50:22 AM] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED: Completed in 0ms
[10-14-2024 11:50:22 AM] csv process: Completed in 28ms
[10-14-2024 11:51:17 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:51:17 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:51:17 AM] Flet app has started...
[10-14-2024 11:51:17 AM] App session started
[10-14-2024 11:51:39 AM] INVALID DATE FOUND: Completed in 0ms
[10-14-2024 11:51:39 AM] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED: Completed in 0ms
[10-14-2024 11:51:39 AM] csv process: Completed in 8ms
[10-14-2024 11:52:06 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:52:06 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:52:06 AM] Flet app has started...
[10-14-2024 11:52:06 AM] App session started
[10-14-2024 11:52:14 AM] INVALID DATE FOUND: Completed in 0ms
[10-14-2024 11:52:14 AM] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED: Completed in 0ms
[10-14-2024 11:52:14 AM] csv process: Completed in 13ms
[10-14-2024 11:53:20 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:53:20 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:53:20 AM] Flet app has started...
[10-14-2024 11:53:20 AM] App session started
[10-14-2024 11:53:29 AM] csv process: Completed in 670ms
[10-14-2024 11:54:02 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:54:02 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:54:02 AM] Flet app has started...
[10-14-2024 11:54:02 AM] App session started
[10-14-2024 11:54:03 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:54:03 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:54:03 AM] Flet app has started...
[10-14-2024 11:54:03 AM] App session started
[10-14-2024 11:54:10 AM] INVALID DATE FOUND: Completed in 0ms
[10-14-2024 11:54:10 AM] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED: Completed in 0ms
[10-14-2024 11:54:10 AM] csv process: Completed in 13ms
[10-14-2024 11:54:59 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 11:54:59 AM] Starting up TCP server on localhost:61638
[10-14-2024 11:54:59 AM] Flet app has started...
[10-14-2024 11:54:59 AM] App session started
[10-14-2024 11:55:08 AM] INVALID DATE FOUND: Completed in 0ms
[10-14-2024 11:55:08 AM] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED: Completed in 0ms
[10-14-2024 11:55:08 AM] csv process: Completed in 12ms
[10-14-2024 01:10:12 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 01:10:12 PM] Starting up TCP server on localhost:52475
[10-14-2024 01:10:12 PM] Flet app has started...
[10-14-2024 01:10:13 PM] App session started
[10-14-2024 01:14:12 PM] csv process: Completed in 1025ms
[10-14-2024 01:15:16 PM] Service Closed: Completed in 0ms
[10-14-2024 01:35:51 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 01:35:51 PM] Starting up TCP server on localhost:56014
[10-14-2024 01:35:51 PM] Flet app has started...
[10-14-2024 01:35:52 PM] App session started
[10-14-2024 01:37:26 PM] csv process: Completed in 1080ms
[10-14-2024 01:49:15 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 01:49:15 PM] Starting up TCP server on localhost:56014
[10-14-2024 01:49:15 PM] Flet app has started...
[10-14-2024 01:49:16 PM] App session started
[10-14-2024 01:50:33 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 01:50:33 PM] Starting up TCP server on localhost:56014
[10-14-2024 01:50:33 PM] Flet app has started...
[10-14-2024 01:50:43 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 01:50:43 PM] Starting up TCP server on localhost:62354
[10-14-2024 01:50:43 PM] Flet app has started...
[10-14-2024 01:50:43 PM] App session started
[10-14-2024 01:51:30 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 01:51:30 PM] Starting up TCP server on localhost:62354
[10-14-2024 01:51:30 PM] Flet app has started...
[10-14-2024 01:51:31 PM] App session started
[10-14-2024 01:51:53 PM] csv process: Completed in 315ms
[10-14-2024 01:59:11 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 01:59:11 PM] Starting up TCP server on localhost:62354
[10-14-2024 01:59:11 PM] Flet app has started...
[10-14-2024 01:59:13 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 01:59:13 PM] Starting up TCP server on localhost:62354
[10-14-2024 01:59:13 PM] Flet app has started...
[10-14-2024 01:59:22 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 01:59:22 PM] Starting up TCP server on localhost:64024
[10-14-2024 01:59:22 PM] Flet app has started...
[10-14-2024 01:59:22 PM] App session started
[10-14-2024 01:59:38 PM] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED: Completed in 0ms
[10-14-2024 01:59:38 PM] csv process: Completed in 212ms
[10-14-2024 02:00:39 PM] Service Closed: Completed in 0ms
[10-14-2024 02:00:40 PM] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED: Completed in 0ms
[10-14-2024 02:00:40 PM] csv process: Completed in 297ms
[10-14-2024 02:03:10 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 02:03:10 PM] Starting up TCP server on localhost:64024
[10-14-2024 02:03:10 PM] Flet app has started...
[10-14-2024 02:03:10 PM] App session started
[10-14-2024 02:03:12 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 02:03:12 PM] Starting up TCP server on localhost:64024
[10-14-2024 02:03:12 PM] Flet app has started...
[10-14-2024 02:03:12 PM] App session started
[10-14-2024 02:03:24 PM] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED: Completed in 0ms
[10-14-2024 02:03:24 PM] csv process: Completed in 205ms
[10-14-2024 02:03:35 PM] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED: Completed in 0ms
[10-14-2024 02:03:35 PM] csv process: Completed in 186ms
[10-14-2024 02:04:16 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 02:04:16 PM] Starting up TCP server on localhost:64024
[10-14-2024 02:04:16 PM] Flet app has started...
[10-14-2024 02:04:17 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 02:04:17 PM] Starting up TCP server on localhost:64024
[10-14-2024 02:04:17 PM] Flet app has started...
[10-14-2024 02:04:18 PM] App session started
[10-14-2024 02:04:27 PM] Future exception was never retrieved
future: <Future finished exception=KeyError(-1)>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: -1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 190, in main_service
    process_file()
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 147, in process_file
    print(csv_file[-1])
          ~~~~~~~~^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: -1
[10-14-2024 02:04:56 PM] Service Closed: Completed in 0ms
[10-14-2024 02:06:00 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 02:06:00 PM] Starting up TCP server on localhost:64024
[10-14-2024 02:06:00 PM] Flet app has started...
[10-14-2024 02:06:00 PM] App session started
[10-14-2024 02:06:11 PM] csv process: Completed in 1375ms
[10-14-2024 02:06:11 PM] Service Closed: Completed in 0ms
[10-14-2024 02:11:16 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 02:11:16 PM] Starting up TCP server on localhost:64024
[10-14-2024 02:11:16 PM] Flet app has started...
[10-14-2024 02:11:16 PM] App session started
[10-14-2024 02:11:37 PM] Future exception was never retrieved
future: <Future finished exception=KeyError('[-1] not found in axis')>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 190, in main_service
    process_file()
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\csv_filter.py", line 148, in process_file
    csv_file.drop(-1)
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 5581, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 4788, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 4830, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 7070, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: '[-1] not found in axis'
[10-14-2024 02:11:48 PM] Service Closed: Completed in 0ms
[10-14-2024 02:15:42 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 02:15:42 PM] Starting up TCP server on localhost:64024
[10-14-2024 02:15:42 PM] Flet app has started...
[10-14-2024 02:15:44 PM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\FE_tests\assets
[10-14-2024 02:15:44 PM] Starting up TCP server on localhost:64024
[10-14-2024 02:15:44 PM] Flet app has started...
[10-14-2024 02:15:44 PM] App session started
[10-14-2024 02:15:58 PM] csv process: Completed in 1486ms
[10-14-2024 03:35:35 PM] csv process: Completed in 2563ms
